FROM golang:1.24-alpine

RUN apk add --no-cache tzdata git
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 4000
EXPOSE 40000

CMD ["dlv", "debug", "./cmd/api", "--build-flags=-buildvcs=false", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient", "--continue"]